image:
  repository: gaiaadm/pumba
  tag: 0.6.4
  pullPolicy: Always

pumbaSelfKill: false

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}

resources:
  requests:
    cpu: 10m
    memory: 5Mi
  limits:
    cpu: 100m
    memory: 20M

pumba:
  args: [--random, --interval, "3m", kill, --signal, "SIGKILL"]
